/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateWellsInput = {
  api: string,
  wellname: string,
  operator?: string | null,
  operatorno?: number | null,
  fieldname?: string | null,
  ground_ele?: string | null,
  kelly_elev?: string | null,
  drkfloor_e?: string | null,
  coordssurf?: string | null,
  coordssu_1?: string | null,
  utmzone?: number | null,
  latitude?: number | null,
  longitude?: number | null,
  footagens?: number | null,
  dir_ns?: string | null,
  footageew?: number | null,
  dir_ew?: string | null,
  qtrqtr?: string | null,
  section?: number | null,
  township?: string | null,
  townshipdi?: string | null,
  range?: string | null,
  rangedir?: string | null,
  meridian?: string | null,
  county?: string | null,
  dir_horiz?: string | null,
  dir_vert?: string | null,
  dir_direct?: string | null,
  confidenti?: string | null,
  confreldat?: string | null,
  leasenumbe?: string | null,
  leasetype?: string | null,
  surfaceown?: string | null,
  abandondat?: string | null,
  wellstatus?: string | null,
  welltype?: string | null,
  totcum_oil?: string | null,
  totcum_gas?: string | null,
  totcum_wat?: string | null,
  indiantrib?: string | null,
  multi_lats?: number | null,
  originalfi?: string | null,
  unitname?: string | null,
  gisstatust?: string | null,
  origcompld?: string | null,
  jurisdicti?: string | null,
  forklift_h?: string | null,
  globalid?: string | null,
  extent?: string | null,
  formationtopdepths?: number | null,
  netpay?: string | null,
  netsand?: string | null,
  reportsid?: string | null,
  tdsnavajo?: string | null,
  tdswingate?: string | null,
  thickness?: number | null,
  _version?: number | null,
};

export type ModelWellsConditionInput = {
  wellname?: ModelStringInput | null,
  operator?: ModelStringInput | null,
  operatorno?: ModelIntInput | null,
  fieldname?: ModelStringInput | null,
  ground_ele?: ModelStringInput | null,
  kelly_elev?: ModelStringInput | null,
  drkfloor_e?: ModelStringInput | null,
  coordssurf?: ModelStringInput | null,
  coordssu_1?: ModelStringInput | null,
  utmzone?: ModelIntInput | null,
  latitude?: ModelFloatInput | null,
  longitude?: ModelFloatInput | null,
  footagens?: ModelIntInput | null,
  dir_ns?: ModelStringInput | null,
  footageew?: ModelIntInput | null,
  dir_ew?: ModelStringInput | null,
  qtrqtr?: ModelStringInput | null,
  section?: ModelIntInput | null,
  township?: ModelStringInput | null,
  townshipdi?: ModelStringInput | null,
  range?: ModelStringInput | null,
  rangedir?: ModelStringInput | null,
  meridian?: ModelStringInput | null,
  county?: ModelStringInput | null,
  dir_horiz?: ModelStringInput | null,
  dir_vert?: ModelStringInput | null,
  dir_direct?: ModelStringInput | null,
  confidenti?: ModelStringInput | null,
  confreldat?: ModelStringInput | null,
  leasenumbe?: ModelStringInput | null,
  leasetype?: ModelStringInput | null,
  surfaceown?: ModelStringInput | null,
  abandondat?: ModelStringInput | null,
  wellstatus?: ModelStringInput | null,
  welltype?: ModelStringInput | null,
  totcum_oil?: ModelStringInput | null,
  totcum_gas?: ModelStringInput | null,
  totcum_wat?: ModelStringInput | null,
  indiantrib?: ModelStringInput | null,
  multi_lats?: ModelIntInput | null,
  originalfi?: ModelStringInput | null,
  unitname?: ModelStringInput | null,
  gisstatust?: ModelStringInput | null,
  origcompld?: ModelStringInput | null,
  jurisdicti?: ModelStringInput | null,
  forklift_h?: ModelStringInput | null,
  globalid?: ModelStringInput | null,
  extent?: ModelStringInput | null,
  formationtopdepths?: ModelFloatInput | null,
  netpay?: ModelStringInput | null,
  netsand?: ModelStringInput | null,
  reportsid?: ModelStringInput | null,
  tdsnavajo?: ModelStringInput | null,
  tdswingate?: ModelStringInput | null,
  thickness?: ModelFloatInput | null,
  and?: Array< ModelWellsConditionInput | null > | null,
  or?: Array< ModelWellsConditionInput | null > | null,
  not?: ModelWellsConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type Wells = {
  __typename: "Wells",
  api: string,
  wellname: string,
  operator?: string | null,
  operatorno?: number | null,
  fieldname?: string | null,
  ground_ele?: string | null,
  kelly_elev?: string | null,
  drkfloor_e?: string | null,
  coordssurf?: string | null,
  coordssu_1?: string | null,
  utmzone?: number | null,
  latitude?: number | null,
  longitude?: number | null,
  footagens?: number | null,
  dir_ns?: string | null,
  footageew?: number | null,
  dir_ew?: string | null,
  qtrqtr?: string | null,
  section?: number | null,
  township?: string | null,
  townshipdi?: string | null,
  range?: string | null,
  rangedir?: string | null,
  meridian?: string | null,
  county?: string | null,
  dir_horiz?: string | null,
  dir_vert?: string | null,
  dir_direct?: string | null,
  confidenti?: string | null,
  confreldat?: string | null,
  leasenumbe?: string | null,
  leasetype?: string | null,
  surfaceown?: string | null,
  abandondat?: string | null,
  wellstatus?: string | null,
  welltype?: string | null,
  totcum_oil?: string | null,
  totcum_gas?: string | null,
  totcum_wat?: string | null,
  indiantrib?: string | null,
  multi_lats?: number | null,
  originalfi?: string | null,
  unitname?: string | null,
  gisstatust?: string | null,
  origcompld?: string | null,
  jurisdicti?: string | null,
  forklift_h?: string | null,
  globalid?: string | null,
  extent?: string | null,
  formationtopdepths?: number | null,
  netpay?: string | null,
  netsand?: string | null,
  reportsid?: string | null,
  tdsnavajo?: string | null,
  tdswingate?: string | null,
  thickness?: number | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type UpdateWellsInput = {
  api: string,
  wellname?: string | null,
  operator?: string | null,
  operatorno?: number | null,
  fieldname?: string | null,
  ground_ele?: string | null,
  kelly_elev?: string | null,
  drkfloor_e?: string | null,
  coordssurf?: string | null,
  coordssu_1?: string | null,
  utmzone?: number | null,
  latitude?: number | null,
  longitude?: number | null,
  footagens?: number | null,
  dir_ns?: string | null,
  footageew?: number | null,
  dir_ew?: string | null,
  qtrqtr?: string | null,
  section?: number | null,
  township?: string | null,
  townshipdi?: string | null,
  range?: string | null,
  rangedir?: string | null,
  meridian?: string | null,
  county?: string | null,
  dir_horiz?: string | null,
  dir_vert?: string | null,
  dir_direct?: string | null,
  confidenti?: string | null,
  confreldat?: string | null,
  leasenumbe?: string | null,
  leasetype?: string | null,
  surfaceown?: string | null,
  abandondat?: string | null,
  wellstatus?: string | null,
  welltype?: string | null,
  totcum_oil?: string | null,
  totcum_gas?: string | null,
  totcum_wat?: string | null,
  indiantrib?: string | null,
  multi_lats?: number | null,
  originalfi?: string | null,
  unitname?: string | null,
  gisstatust?: string | null,
  origcompld?: string | null,
  jurisdicti?: string | null,
  forklift_h?: string | null,
  globalid?: string | null,
  extent?: string | null,
  formationtopdepths?: number | null,
  netpay?: string | null,
  netsand?: string | null,
  reportsid?: string | null,
  tdsnavajo?: string | null,
  tdswingate?: string | null,
  thickness?: number | null,
  _version?: number | null,
};

export type DeleteWellsInput = {
  api: string,
  _version?: number | null,
};

export type ModelWellsFilterInput = {
  api?: ModelIDInput | null,
  wellname?: ModelStringInput | null,
  operator?: ModelStringInput | null,
  operatorno?: ModelIntInput | null,
  fieldname?: ModelStringInput | null,
  ground_ele?: ModelStringInput | null,
  kelly_elev?: ModelStringInput | null,
  drkfloor_e?: ModelStringInput | null,
  coordssurf?: ModelStringInput | null,
  coordssu_1?: ModelStringInput | null,
  utmzone?: ModelIntInput | null,
  latitude?: ModelFloatInput | null,
  longitude?: ModelFloatInput | null,
  footagens?: ModelIntInput | null,
  dir_ns?: ModelStringInput | null,
  footageew?: ModelIntInput | null,
  dir_ew?: ModelStringInput | null,
  qtrqtr?: ModelStringInput | null,
  section?: ModelIntInput | null,
  township?: ModelStringInput | null,
  townshipdi?: ModelStringInput | null,
  range?: ModelStringInput | null,
  rangedir?: ModelStringInput | null,
  meridian?: ModelStringInput | null,
  county?: ModelStringInput | null,
  dir_horiz?: ModelStringInput | null,
  dir_vert?: ModelStringInput | null,
  dir_direct?: ModelStringInput | null,
  confidenti?: ModelStringInput | null,
  confreldat?: ModelStringInput | null,
  leasenumbe?: ModelStringInput | null,
  leasetype?: ModelStringInput | null,
  surfaceown?: ModelStringInput | null,
  abandondat?: ModelStringInput | null,
  wellstatus?: ModelStringInput | null,
  welltype?: ModelStringInput | null,
  totcum_oil?: ModelStringInput | null,
  totcum_gas?: ModelStringInput | null,
  totcum_wat?: ModelStringInput | null,
  indiantrib?: ModelStringInput | null,
  multi_lats?: ModelIntInput | null,
  originalfi?: ModelStringInput | null,
  unitname?: ModelStringInput | null,
  gisstatust?: ModelStringInput | null,
  origcompld?: ModelStringInput | null,
  jurisdicti?: ModelStringInput | null,
  forklift_h?: ModelStringInput | null,
  globalid?: ModelStringInput | null,
  extent?: ModelStringInput | null,
  formationtopdepths?: ModelFloatInput | null,
  netpay?: ModelStringInput | null,
  netsand?: ModelStringInput | null,
  reportsid?: ModelStringInput | null,
  tdsnavajo?: ModelStringInput | null,
  tdswingate?: ModelStringInput | null,
  thickness?: ModelFloatInput | null,
  and?: Array< ModelWellsFilterInput | null > | null,
  or?: Array< ModelWellsFilterInput | null > | null,
  not?: ModelWellsFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelWellsConnection = {
  __typename: "ModelWellsConnection",
  items:  Array<Wells | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type CreateWellsMutationVariables = {
  input: CreateWellsInput,
  condition?: ModelWellsConditionInput | null,
};

export type CreateWellsMutation = {
  createWells?:  {
    __typename: "Wells",
    api: string,
    wellname: string,
    operator?: string | null,
    operatorno?: number | null,
    fieldname?: string | null,
    ground_ele?: string | null,
    kelly_elev?: string | null,
    drkfloor_e?: string | null,
    coordssurf?: string | null,
    coordssu_1?: string | null,
    utmzone?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footagens?: number | null,
    dir_ns?: string | null,
    footageew?: number | null,
    dir_ew?: string | null,
    qtrqtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipdi?: string | null,
    range?: string | null,
    rangedir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dir_horiz?: string | null,
    dir_vert?: string | null,
    dir_direct?: string | null,
    confidenti?: string | null,
    confreldat?: string | null,
    leasenumbe?: string | null,
    leasetype?: string | null,
    surfaceown?: string | null,
    abandondat?: string | null,
    wellstatus?: string | null,
    welltype?: string | null,
    totcum_oil?: string | null,
    totcum_gas?: string | null,
    totcum_wat?: string | null,
    indiantrib?: string | null,
    multi_lats?: number | null,
    originalfi?: string | null,
    unitname?: string | null,
    gisstatust?: string | null,
    origcompld?: string | null,
    jurisdicti?: string | null,
    forklift_h?: string | null,
    globalid?: string | null,
    extent?: string | null,
    formationtopdepths?: number | null,
    netpay?: string | null,
    netsand?: string | null,
    reportsid?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    thickness?: number | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateWellsMutationVariables = {
  input: UpdateWellsInput,
  condition?: ModelWellsConditionInput | null,
};

export type UpdateWellsMutation = {
  updateWells?:  {
    __typename: "Wells",
    api: string,
    wellname: string,
    operator?: string | null,
    operatorno?: number | null,
    fieldname?: string | null,
    ground_ele?: string | null,
    kelly_elev?: string | null,
    drkfloor_e?: string | null,
    coordssurf?: string | null,
    coordssu_1?: string | null,
    utmzone?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footagens?: number | null,
    dir_ns?: string | null,
    footageew?: number | null,
    dir_ew?: string | null,
    qtrqtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipdi?: string | null,
    range?: string | null,
    rangedir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dir_horiz?: string | null,
    dir_vert?: string | null,
    dir_direct?: string | null,
    confidenti?: string | null,
    confreldat?: string | null,
    leasenumbe?: string | null,
    leasetype?: string | null,
    surfaceown?: string | null,
    abandondat?: string | null,
    wellstatus?: string | null,
    welltype?: string | null,
    totcum_oil?: string | null,
    totcum_gas?: string | null,
    totcum_wat?: string | null,
    indiantrib?: string | null,
    multi_lats?: number | null,
    originalfi?: string | null,
    unitname?: string | null,
    gisstatust?: string | null,
    origcompld?: string | null,
    jurisdicti?: string | null,
    forklift_h?: string | null,
    globalid?: string | null,
    extent?: string | null,
    formationtopdepths?: number | null,
    netpay?: string | null,
    netsand?: string | null,
    reportsid?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    thickness?: number | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteWellsMutationVariables = {
  input: DeleteWellsInput,
  condition?: ModelWellsConditionInput | null,
};

export type DeleteWellsMutation = {
  deleteWells?:  {
    __typename: "Wells",
    api: string,
    wellname: string,
    operator?: string | null,
    operatorno?: number | null,
    fieldname?: string | null,
    ground_ele?: string | null,
    kelly_elev?: string | null,
    drkfloor_e?: string | null,
    coordssurf?: string | null,
    coordssu_1?: string | null,
    utmzone?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footagens?: number | null,
    dir_ns?: string | null,
    footageew?: number | null,
    dir_ew?: string | null,
    qtrqtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipdi?: string | null,
    range?: string | null,
    rangedir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dir_horiz?: string | null,
    dir_vert?: string | null,
    dir_direct?: string | null,
    confidenti?: string | null,
    confreldat?: string | null,
    leasenumbe?: string | null,
    leasetype?: string | null,
    surfaceown?: string | null,
    abandondat?: string | null,
    wellstatus?: string | null,
    welltype?: string | null,
    totcum_oil?: string | null,
    totcum_gas?: string | null,
    totcum_wat?: string | null,
    indiantrib?: string | null,
    multi_lats?: number | null,
    originalfi?: string | null,
    unitname?: string | null,
    gisstatust?: string | null,
    origcompld?: string | null,
    jurisdicti?: string | null,
    forklift_h?: string | null,
    globalid?: string | null,
    extent?: string | null,
    formationtopdepths?: number | null,
    netpay?: string | null,
    netsand?: string | null,
    reportsid?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    thickness?: number | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type GetWellsQueryVariables = {
  api: string,
};

export type GetWellsQuery = {
  getWells?:  {
    __typename: "Wells",
    api: string,
    wellname: string,
    operator?: string | null,
    operatorno?: number | null,
    fieldname?: string | null,
    ground_ele?: string | null,
    kelly_elev?: string | null,
    drkfloor_e?: string | null,
    coordssurf?: string | null,
    coordssu_1?: string | null,
    utmzone?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footagens?: number | null,
    dir_ns?: string | null,
    footageew?: number | null,
    dir_ew?: string | null,
    qtrqtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipdi?: string | null,
    range?: string | null,
    rangedir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dir_horiz?: string | null,
    dir_vert?: string | null,
    dir_direct?: string | null,
    confidenti?: string | null,
    confreldat?: string | null,
    leasenumbe?: string | null,
    leasetype?: string | null,
    surfaceown?: string | null,
    abandondat?: string | null,
    wellstatus?: string | null,
    welltype?: string | null,
    totcum_oil?: string | null,
    totcum_gas?: string | null,
    totcum_wat?: string | null,
    indiantrib?: string | null,
    multi_lats?: number | null,
    originalfi?: string | null,
    unitname?: string | null,
    gisstatust?: string | null,
    origcompld?: string | null,
    jurisdicti?: string | null,
    forklift_h?: string | null,
    globalid?: string | null,
    extent?: string | null,
    formationtopdepths?: number | null,
    netpay?: string | null,
    netsand?: string | null,
    reportsid?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    thickness?: number | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListWellsQueryVariables = {
  api?: string | null,
  filter?: ModelWellsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  sortDirection?: ModelSortDirection | null,
};

export type ListWellsQuery = {
  listWells?:  {
    __typename: "ModelWellsConnection",
    items:  Array< {
      __typename: "Wells",
      api: string,
      wellname: string,
      operator?: string | null,
      operatorno?: number | null,
      fieldname?: string | null,
      ground_ele?: string | null,
      kelly_elev?: string | null,
      drkfloor_e?: string | null,
      coordssurf?: string | null,
      coordssu_1?: string | null,
      utmzone?: number | null,
      latitude?: number | null,
      longitude?: number | null,
      footagens?: number | null,
      dir_ns?: string | null,
      footageew?: number | null,
      dir_ew?: string | null,
      qtrqtr?: string | null,
      section?: number | null,
      township?: string | null,
      townshipdi?: string | null,
      range?: string | null,
      rangedir?: string | null,
      meridian?: string | null,
      county?: string | null,
      dir_horiz?: string | null,
      dir_vert?: string | null,
      dir_direct?: string | null,
      confidenti?: string | null,
      confreldat?: string | null,
      leasenumbe?: string | null,
      leasetype?: string | null,
      surfaceown?: string | null,
      abandondat?: string | null,
      wellstatus?: string | null,
      welltype?: string | null,
      totcum_oil?: string | null,
      totcum_gas?: string | null,
      totcum_wat?: string | null,
      indiantrib?: string | null,
      multi_lats?: number | null,
      originalfi?: string | null,
      unitname?: string | null,
      gisstatust?: string | null,
      origcompld?: string | null,
      jurisdicti?: string | null,
      forklift_h?: string | null,
      globalid?: string | null,
      extent?: string | null,
      formationtopdepths?: number | null,
      netpay?: string | null,
      netsand?: string | null,
      reportsid?: string | null,
      tdsnavajo?: string | null,
      tdswingate?: string | null,
      thickness?: number | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncWellsQueryVariables = {
  filter?: ModelWellsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncWellsQuery = {
  syncWells?:  {
    __typename: "ModelWellsConnection",
    items:  Array< {
      __typename: "Wells",
      api: string,
      wellname: string,
      operator?: string | null,
      operatorno?: number | null,
      fieldname?: string | null,
      ground_ele?: string | null,
      kelly_elev?: string | null,
      drkfloor_e?: string | null,
      coordssurf?: string | null,
      coordssu_1?: string | null,
      utmzone?: number | null,
      latitude?: number | null,
      longitude?: number | null,
      footagens?: number | null,
      dir_ns?: string | null,
      footageew?: number | null,
      dir_ew?: string | null,
      qtrqtr?: string | null,
      section?: number | null,
      township?: string | null,
      townshipdi?: string | null,
      range?: string | null,
      rangedir?: string | null,
      meridian?: string | null,
      county?: string | null,
      dir_horiz?: string | null,
      dir_vert?: string | null,
      dir_direct?: string | null,
      confidenti?: string | null,
      confreldat?: string | null,
      leasenumbe?: string | null,
      leasetype?: string | null,
      surfaceown?: string | null,
      abandondat?: string | null,
      wellstatus?: string | null,
      welltype?: string | null,
      totcum_oil?: string | null,
      totcum_gas?: string | null,
      totcum_wat?: string | null,
      indiantrib?: string | null,
      multi_lats?: number | null,
      originalfi?: string | null,
      unitname?: string | null,
      gisstatust?: string | null,
      origcompld?: string | null,
      jurisdicti?: string | null,
      forklift_h?: string | null,
      globalid?: string | null,
      extent?: string | null,
      formationtopdepths?: number | null,
      netpay?: string | null,
      netsand?: string | null,
      reportsid?: string | null,
      tdsnavajo?: string | null,
      tdswingate?: string | null,
      thickness?: number | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OnCreateWellsSubscription = {
  onCreateWells?:  {
    __typename: "Wells",
    api: string,
    wellname: string,
    operator?: string | null,
    operatorno?: number | null,
    fieldname?: string | null,
    ground_ele?: string | null,
    kelly_elev?: string | null,
    drkfloor_e?: string | null,
    coordssurf?: string | null,
    coordssu_1?: string | null,
    utmzone?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footagens?: number | null,
    dir_ns?: string | null,
    footageew?: number | null,
    dir_ew?: string | null,
    qtrqtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipdi?: string | null,
    range?: string | null,
    rangedir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dir_horiz?: string | null,
    dir_vert?: string | null,
    dir_direct?: string | null,
    confidenti?: string | null,
    confreldat?: string | null,
    leasenumbe?: string | null,
    leasetype?: string | null,
    surfaceown?: string | null,
    abandondat?: string | null,
    wellstatus?: string | null,
    welltype?: string | null,
    totcum_oil?: string | null,
    totcum_gas?: string | null,
    totcum_wat?: string | null,
    indiantrib?: string | null,
    multi_lats?: number | null,
    originalfi?: string | null,
    unitname?: string | null,
    gisstatust?: string | null,
    origcompld?: string | null,
    jurisdicti?: string | null,
    forklift_h?: string | null,
    globalid?: string | null,
    extent?: string | null,
    formationtopdepths?: number | null,
    netpay?: string | null,
    netsand?: string | null,
    reportsid?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    thickness?: number | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateWellsSubscription = {
  onUpdateWells?:  {
    __typename: "Wells",
    api: string,
    wellname: string,
    operator?: string | null,
    operatorno?: number | null,
    fieldname?: string | null,
    ground_ele?: string | null,
    kelly_elev?: string | null,
    drkfloor_e?: string | null,
    coordssurf?: string | null,
    coordssu_1?: string | null,
    utmzone?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footagens?: number | null,
    dir_ns?: string | null,
    footageew?: number | null,
    dir_ew?: string | null,
    qtrqtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipdi?: string | null,
    range?: string | null,
    rangedir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dir_horiz?: string | null,
    dir_vert?: string | null,
    dir_direct?: string | null,
    confidenti?: string | null,
    confreldat?: string | null,
    leasenumbe?: string | null,
    leasetype?: string | null,
    surfaceown?: string | null,
    abandondat?: string | null,
    wellstatus?: string | null,
    welltype?: string | null,
    totcum_oil?: string | null,
    totcum_gas?: string | null,
    totcum_wat?: string | null,
    indiantrib?: string | null,
    multi_lats?: number | null,
    originalfi?: string | null,
    unitname?: string | null,
    gisstatust?: string | null,
    origcompld?: string | null,
    jurisdicti?: string | null,
    forklift_h?: string | null,
    globalid?: string | null,
    extent?: string | null,
    formationtopdepths?: number | null,
    netpay?: string | null,
    netsand?: string | null,
    reportsid?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    thickness?: number | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteWellsSubscription = {
  onDeleteWells?:  {
    __typename: "Wells",
    api: string,
    wellname: string,
    operator?: string | null,
    operatorno?: number | null,
    fieldname?: string | null,
    ground_ele?: string | null,
    kelly_elev?: string | null,
    drkfloor_e?: string | null,
    coordssurf?: string | null,
    coordssu_1?: string | null,
    utmzone?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footagens?: number | null,
    dir_ns?: string | null,
    footageew?: number | null,
    dir_ew?: string | null,
    qtrqtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipdi?: string | null,
    range?: string | null,
    rangedir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dir_horiz?: string | null,
    dir_vert?: string | null,
    dir_direct?: string | null,
    confidenti?: string | null,
    confreldat?: string | null,
    leasenumbe?: string | null,
    leasetype?: string | null,
    surfaceown?: string | null,
    abandondat?: string | null,
    wellstatus?: string | null,
    welltype?: string | null,
    totcum_oil?: string | null,
    totcum_gas?: string | null,
    totcum_wat?: string | null,
    indiantrib?: string | null,
    multi_lats?: number | null,
    originalfi?: string | null,
    unitname?: string | null,
    gisstatust?: string | null,
    origcompld?: string | null,
    jurisdicti?: string | null,
    forklift_h?: string | null,
    globalid?: string | null,
    extent?: string | null,
    formationtopdepths?: number | null,
    netpay?: string | null,
    netsand?: string | null,
    reportsid?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    thickness?: number | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};
