/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateWellsInput = {
  api: string,
  wellName: string,
  operator?: string | null,
  operatorNo?: number | null,
  fieldName?: string | null,
  groundElev?: string | null,
  kellyElev?: string | null,
  drkFloorElev?: string | null,
  coordsSurfN?: string | null,
  coordsSurfE?: string | null,
  utm?: number | null,
  latitude?: number | null,
  longitude?: number | null,
  footageNS?: number | null,
  dirNS?: string | null,
  footageEW?: string | null,
  dirEW?: string | null,
  qtrQtr?: string | null,
  section?: number | null,
  township?: string | null,
  townshipDir?: string | null,
  range?: string | null,
  rangeDir?: string | null,
  meridian?: string | null,
  county?: string | null,
  dirHoriz?: string | null,
  dirVert?: string | null,
  dirDirect?: string | null,
  confidential?: string | null,
  confRelDate?: string | null,
  leaseNumber?: string | null,
  leaseType?: string | null,
  surfaceOwner?: string | null,
  abandonDate?: string | null,
  wellStatus?: string | null,
  totCumOil?: string | null,
  totCumGas?: string | null,
  totCumWater?: string | null,
  indianTribe?: string | null,
  multiLats?: number | null,
  origianlField?: string | null,
  unitName?: string | null,
  gisstatusType?: string | null,
  origComplDate?: string | null,
  jurisdiction?: string | null,
  tdsnavajo?: string | null,
  tdswingate?: string | null,
  id?: string | null,
  _version?: number | null,
};

export type ModelWellsConditionInput = {
  api?: ModelIDInput | null,
  wellName?: ModelStringInput | null,
  operator?: ModelStringInput | null,
  operatorNo?: ModelIntInput | null,
  fieldName?: ModelStringInput | null,
  groundElev?: ModelStringInput | null,
  kellyElev?: ModelStringInput | null,
  drkFloorElev?: ModelStringInput | null,
  coordsSurfN?: ModelStringInput | null,
  coordsSurfE?: ModelStringInput | null,
  utm?: ModelIntInput | null,
  latitude?: ModelFloatInput | null,
  longitude?: ModelFloatInput | null,
  footageNS?: ModelIntInput | null,
  dirNS?: ModelStringInput | null,
  footageEW?: ModelStringInput | null,
  dirEW?: ModelStringInput | null,
  qtrQtr?: ModelStringInput | null,
  section?: ModelIntInput | null,
  township?: ModelStringInput | null,
  townshipDir?: ModelStringInput | null,
  range?: ModelStringInput | null,
  rangeDir?: ModelStringInput | null,
  meridian?: ModelStringInput | null,
  county?: ModelStringInput | null,
  dirHoriz?: ModelStringInput | null,
  dirVert?: ModelStringInput | null,
  dirDirect?: ModelStringInput | null,
  confidential?: ModelStringInput | null,
  confRelDate?: ModelStringInput | null,
  leaseNumber?: ModelStringInput | null,
  leaseType?: ModelStringInput | null,
  surfaceOwner?: ModelStringInput | null,
  abandonDate?: ModelStringInput | null,
  wellStatus?: ModelStringInput | null,
  totCumOil?: ModelStringInput | null,
  totCumGas?: ModelStringInput | null,
  totCumWater?: ModelStringInput | null,
  indianTribe?: ModelStringInput | null,
  multiLats?: ModelIntInput | null,
  origianlField?: ModelStringInput | null,
  unitName?: ModelStringInput | null,
  gisstatusType?: ModelStringInput | null,
  origComplDate?: ModelStringInput | null,
  jurisdiction?: ModelStringInput | null,
  tdsnavajo?: ModelStringInput | null,
  tdswingate?: ModelStringInput | null,
  and?: Array< ModelWellsConditionInput | null > | null,
  or?: Array< ModelWellsConditionInput | null > | null,
  not?: ModelWellsConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type Wells = {
  __typename: "Wells",
  api: string,
  wellName: string,
  operator?: string | null,
  operatorNo?: number | null,
  fieldName?: string | null,
  groundElev?: string | null,
  kellyElev?: string | null,
  drkFloorElev?: string | null,
  coordsSurfN?: string | null,
  coordsSurfE?: string | null,
  utm?: number | null,
  latitude?: number | null,
  longitude?: number | null,
  footageNS?: number | null,
  dirNS?: string | null,
  footageEW?: string | null,
  dirEW?: string | null,
  qtrQtr?: string | null,
  section?: number | null,
  township?: string | null,
  townshipDir?: string | null,
  range?: string | null,
  rangeDir?: string | null,
  meridian?: string | null,
  county?: string | null,
  dirHoriz?: string | null,
  dirVert?: string | null,
  dirDirect?: string | null,
  confidential?: string | null,
  confRelDate?: string | null,
  leaseNumber?: string | null,
  leaseType?: string | null,
  surfaceOwner?: string | null,
  abandonDate?: string | null,
  wellStatus?: string | null,
  totCumOil?: string | null,
  totCumGas?: string | null,
  totCumWater?: string | null,
  indianTribe?: string | null,
  multiLats?: number | null,
  origianlField?: string | null,
  unitName?: string | null,
  gisstatusType?: string | null,
  origComplDate?: string | null,
  jurisdiction?: string | null,
  tdsnavajo?: string | null,
  tdswingate?: string | null,
  id: string,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type UpdateWellsInput = {
  api?: string | null,
  wellName?: string | null,
  operator?: string | null,
  operatorNo?: number | null,
  fieldName?: string | null,
  groundElev?: string | null,
  kellyElev?: string | null,
  drkFloorElev?: string | null,
  coordsSurfN?: string | null,
  coordsSurfE?: string | null,
  utm?: number | null,
  latitude?: number | null,
  longitude?: number | null,
  footageNS?: number | null,
  dirNS?: string | null,
  footageEW?: string | null,
  dirEW?: string | null,
  qtrQtr?: string | null,
  section?: number | null,
  township?: string | null,
  townshipDir?: string | null,
  range?: string | null,
  rangeDir?: string | null,
  meridian?: string | null,
  county?: string | null,
  dirHoriz?: string | null,
  dirVert?: string | null,
  dirDirect?: string | null,
  confidential?: string | null,
  confRelDate?: string | null,
  leaseNumber?: string | null,
  leaseType?: string | null,
  surfaceOwner?: string | null,
  abandonDate?: string | null,
  wellStatus?: string | null,
  totCumOil?: string | null,
  totCumGas?: string | null,
  totCumWater?: string | null,
  indianTribe?: string | null,
  multiLats?: number | null,
  origianlField?: string | null,
  unitName?: string | null,
  gisstatusType?: string | null,
  origComplDate?: string | null,
  jurisdiction?: string | null,
  tdsnavajo?: string | null,
  tdswingate?: string | null,
  id: string,
  _version?: number | null,
};

export type DeleteWellsInput = {
  id: string,
  _version?: number | null,
};

export type ModelWellsFilterInput = {
  api?: ModelIDInput | null,
  wellName?: ModelStringInput | null,
  operator?: ModelStringInput | null,
  operatorNo?: ModelIntInput | null,
  fieldName?: ModelStringInput | null,
  groundElev?: ModelStringInput | null,
  kellyElev?: ModelStringInput | null,
  drkFloorElev?: ModelStringInput | null,
  coordsSurfN?: ModelStringInput | null,
  coordsSurfE?: ModelStringInput | null,
  utm?: ModelIntInput | null,
  latitude?: ModelFloatInput | null,
  longitude?: ModelFloatInput | null,
  footageNS?: ModelIntInput | null,
  dirNS?: ModelStringInput | null,
  footageEW?: ModelStringInput | null,
  dirEW?: ModelStringInput | null,
  qtrQtr?: ModelStringInput | null,
  section?: ModelIntInput | null,
  township?: ModelStringInput | null,
  townshipDir?: ModelStringInput | null,
  range?: ModelStringInput | null,
  rangeDir?: ModelStringInput | null,
  meridian?: ModelStringInput | null,
  county?: ModelStringInput | null,
  dirHoriz?: ModelStringInput | null,
  dirVert?: ModelStringInput | null,
  dirDirect?: ModelStringInput | null,
  confidential?: ModelStringInput | null,
  confRelDate?: ModelStringInput | null,
  leaseNumber?: ModelStringInput | null,
  leaseType?: ModelStringInput | null,
  surfaceOwner?: ModelStringInput | null,
  abandonDate?: ModelStringInput | null,
  wellStatus?: ModelStringInput | null,
  totCumOil?: ModelStringInput | null,
  totCumGas?: ModelStringInput | null,
  totCumWater?: ModelStringInput | null,
  indianTribe?: ModelStringInput | null,
  multiLats?: ModelIntInput | null,
  origianlField?: ModelStringInput | null,
  unitName?: ModelStringInput | null,
  gisstatusType?: ModelStringInput | null,
  origComplDate?: ModelStringInput | null,
  jurisdiction?: ModelStringInput | null,
  tdsnavajo?: ModelStringInput | null,
  tdswingate?: ModelStringInput | null,
  and?: Array< ModelWellsFilterInput | null > | null,
  or?: Array< ModelWellsFilterInput | null > | null,
  not?: ModelWellsFilterInput | null,
};

export type ModelWellsConnection = {
  __typename: "ModelWellsConnection",
  items:  Array<Wells | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type CreateWellsMutationVariables = {
  input: CreateWellsInput,
  condition?: ModelWellsConditionInput | null,
};

export type CreateWellsMutation = {
  createWells?:  {
    __typename: "Wells",
    api: string,
    wellName: string,
    operator?: string | null,
    operatorNo?: number | null,
    fieldName?: string | null,
    groundElev?: string | null,
    kellyElev?: string | null,
    drkFloorElev?: string | null,
    coordsSurfN?: string | null,
    coordsSurfE?: string | null,
    utm?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footageNS?: number | null,
    dirNS?: string | null,
    footageEW?: string | null,
    dirEW?: string | null,
    qtrQtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipDir?: string | null,
    range?: string | null,
    rangeDir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dirHoriz?: string | null,
    dirVert?: string | null,
    dirDirect?: string | null,
    confidential?: string | null,
    confRelDate?: string | null,
    leaseNumber?: string | null,
    leaseType?: string | null,
    surfaceOwner?: string | null,
    abandonDate?: string | null,
    wellStatus?: string | null,
    totCumOil?: string | null,
    totCumGas?: string | null,
    totCumWater?: string | null,
    indianTribe?: string | null,
    multiLats?: number | null,
    origianlField?: string | null,
    unitName?: string | null,
    gisstatusType?: string | null,
    origComplDate?: string | null,
    jurisdiction?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateWellsMutationVariables = {
  input: UpdateWellsInput,
  condition?: ModelWellsConditionInput | null,
};

export type UpdateWellsMutation = {
  updateWells?:  {
    __typename: "Wells",
    api: string,
    wellName: string,
    operator?: string | null,
    operatorNo?: number | null,
    fieldName?: string | null,
    groundElev?: string | null,
    kellyElev?: string | null,
    drkFloorElev?: string | null,
    coordsSurfN?: string | null,
    coordsSurfE?: string | null,
    utm?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footageNS?: number | null,
    dirNS?: string | null,
    footageEW?: string | null,
    dirEW?: string | null,
    qtrQtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipDir?: string | null,
    range?: string | null,
    rangeDir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dirHoriz?: string | null,
    dirVert?: string | null,
    dirDirect?: string | null,
    confidential?: string | null,
    confRelDate?: string | null,
    leaseNumber?: string | null,
    leaseType?: string | null,
    surfaceOwner?: string | null,
    abandonDate?: string | null,
    wellStatus?: string | null,
    totCumOil?: string | null,
    totCumGas?: string | null,
    totCumWater?: string | null,
    indianTribe?: string | null,
    multiLats?: number | null,
    origianlField?: string | null,
    unitName?: string | null,
    gisstatusType?: string | null,
    origComplDate?: string | null,
    jurisdiction?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteWellsMutationVariables = {
  input: DeleteWellsInput,
  condition?: ModelWellsConditionInput | null,
};

export type DeleteWellsMutation = {
  deleteWells?:  {
    __typename: "Wells",
    api: string,
    wellName: string,
    operator?: string | null,
    operatorNo?: number | null,
    fieldName?: string | null,
    groundElev?: string | null,
    kellyElev?: string | null,
    drkFloorElev?: string | null,
    coordsSurfN?: string | null,
    coordsSurfE?: string | null,
    utm?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footageNS?: number | null,
    dirNS?: string | null,
    footageEW?: string | null,
    dirEW?: string | null,
    qtrQtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipDir?: string | null,
    range?: string | null,
    rangeDir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dirHoriz?: string | null,
    dirVert?: string | null,
    dirDirect?: string | null,
    confidential?: string | null,
    confRelDate?: string | null,
    leaseNumber?: string | null,
    leaseType?: string | null,
    surfaceOwner?: string | null,
    abandonDate?: string | null,
    wellStatus?: string | null,
    totCumOil?: string | null,
    totCumGas?: string | null,
    totCumWater?: string | null,
    indianTribe?: string | null,
    multiLats?: number | null,
    origianlField?: string | null,
    unitName?: string | null,
    gisstatusType?: string | null,
    origComplDate?: string | null,
    jurisdiction?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type GetWellsQueryVariables = {
  id: string,
};

export type GetWellsQuery = {
  getWells?:  {
    __typename: "Wells",
    api: string,
    wellName: string,
    operator?: string | null,
    operatorNo?: number | null,
    fieldName?: string | null,
    groundElev?: string | null,
    kellyElev?: string | null,
    drkFloorElev?: string | null,
    coordsSurfN?: string | null,
    coordsSurfE?: string | null,
    utm?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footageNS?: number | null,
    dirNS?: string | null,
    footageEW?: string | null,
    dirEW?: string | null,
    qtrQtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipDir?: string | null,
    range?: string | null,
    rangeDir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dirHoriz?: string | null,
    dirVert?: string | null,
    dirDirect?: string | null,
    confidential?: string | null,
    confRelDate?: string | null,
    leaseNumber?: string | null,
    leaseType?: string | null,
    surfaceOwner?: string | null,
    abandonDate?: string | null,
    wellStatus?: string | null,
    totCumOil?: string | null,
    totCumGas?: string | null,
    totCumWater?: string | null,
    indianTribe?: string | null,
    multiLats?: number | null,
    origianlField?: string | null,
    unitName?: string | null,
    gisstatusType?: string | null,
    origComplDate?: string | null,
    jurisdiction?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListWellsQueryVariables = {
  filter?: ModelWellsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListWellsQuery = {
  listWells?:  {
    __typename: "ModelWellsConnection",
    items:  Array< {
      __typename: "Wells",
      api: string,
      wellName: string,
      operator?: string | null,
      operatorNo?: number | null,
      fieldName?: string | null,
      groundElev?: string | null,
      kellyElev?: string | null,
      drkFloorElev?: string | null,
      coordsSurfN?: string | null,
      coordsSurfE?: string | null,
      utm?: number | null,
      latitude?: number | null,
      longitude?: number | null,
      footageNS?: number | null,
      dirNS?: string | null,
      footageEW?: string | null,
      dirEW?: string | null,
      qtrQtr?: string | null,
      section?: number | null,
      township?: string | null,
      townshipDir?: string | null,
      range?: string | null,
      rangeDir?: string | null,
      meridian?: string | null,
      county?: string | null,
      dirHoriz?: string | null,
      dirVert?: string | null,
      dirDirect?: string | null,
      confidential?: string | null,
      confRelDate?: string | null,
      leaseNumber?: string | null,
      leaseType?: string | null,
      surfaceOwner?: string | null,
      abandonDate?: string | null,
      wellStatus?: string | null,
      totCumOil?: string | null,
      totCumGas?: string | null,
      totCumWater?: string | null,
      indianTribe?: string | null,
      multiLats?: number | null,
      origianlField?: string | null,
      unitName?: string | null,
      gisstatusType?: string | null,
      origComplDate?: string | null,
      jurisdiction?: string | null,
      tdsnavajo?: string | null,
      tdswingate?: string | null,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncWellsQueryVariables = {
  filter?: ModelWellsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncWellsQuery = {
  syncWells?:  {
    __typename: "ModelWellsConnection",
    items:  Array< {
      __typename: "Wells",
      api: string,
      wellName: string,
      operator?: string | null,
      operatorNo?: number | null,
      fieldName?: string | null,
      groundElev?: string | null,
      kellyElev?: string | null,
      drkFloorElev?: string | null,
      coordsSurfN?: string | null,
      coordsSurfE?: string | null,
      utm?: number | null,
      latitude?: number | null,
      longitude?: number | null,
      footageNS?: number | null,
      dirNS?: string | null,
      footageEW?: string | null,
      dirEW?: string | null,
      qtrQtr?: string | null,
      section?: number | null,
      township?: string | null,
      townshipDir?: string | null,
      range?: string | null,
      rangeDir?: string | null,
      meridian?: string | null,
      county?: string | null,
      dirHoriz?: string | null,
      dirVert?: string | null,
      dirDirect?: string | null,
      confidential?: string | null,
      confRelDate?: string | null,
      leaseNumber?: string | null,
      leaseType?: string | null,
      surfaceOwner?: string | null,
      abandonDate?: string | null,
      wellStatus?: string | null,
      totCumOil?: string | null,
      totCumGas?: string | null,
      totCumWater?: string | null,
      indianTribe?: string | null,
      multiLats?: number | null,
      origianlField?: string | null,
      unitName?: string | null,
      gisstatusType?: string | null,
      origComplDate?: string | null,
      jurisdiction?: string | null,
      tdsnavajo?: string | null,
      tdswingate?: string | null,
      id: string,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OnCreateWellsSubscription = {
  onCreateWells?:  {
    __typename: "Wells",
    api: string,
    wellName: string,
    operator?: string | null,
    operatorNo?: number | null,
    fieldName?: string | null,
    groundElev?: string | null,
    kellyElev?: string | null,
    drkFloorElev?: string | null,
    coordsSurfN?: string | null,
    coordsSurfE?: string | null,
    utm?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footageNS?: number | null,
    dirNS?: string | null,
    footageEW?: string | null,
    dirEW?: string | null,
    qtrQtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipDir?: string | null,
    range?: string | null,
    rangeDir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dirHoriz?: string | null,
    dirVert?: string | null,
    dirDirect?: string | null,
    confidential?: string | null,
    confRelDate?: string | null,
    leaseNumber?: string | null,
    leaseType?: string | null,
    surfaceOwner?: string | null,
    abandonDate?: string | null,
    wellStatus?: string | null,
    totCumOil?: string | null,
    totCumGas?: string | null,
    totCumWater?: string | null,
    indianTribe?: string | null,
    multiLats?: number | null,
    origianlField?: string | null,
    unitName?: string | null,
    gisstatusType?: string | null,
    origComplDate?: string | null,
    jurisdiction?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateWellsSubscription = {
  onUpdateWells?:  {
    __typename: "Wells",
    api: string,
    wellName: string,
    operator?: string | null,
    operatorNo?: number | null,
    fieldName?: string | null,
    groundElev?: string | null,
    kellyElev?: string | null,
    drkFloorElev?: string | null,
    coordsSurfN?: string | null,
    coordsSurfE?: string | null,
    utm?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footageNS?: number | null,
    dirNS?: string | null,
    footageEW?: string | null,
    dirEW?: string | null,
    qtrQtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipDir?: string | null,
    range?: string | null,
    rangeDir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dirHoriz?: string | null,
    dirVert?: string | null,
    dirDirect?: string | null,
    confidential?: string | null,
    confRelDate?: string | null,
    leaseNumber?: string | null,
    leaseType?: string | null,
    surfaceOwner?: string | null,
    abandonDate?: string | null,
    wellStatus?: string | null,
    totCumOil?: string | null,
    totCumGas?: string | null,
    totCumWater?: string | null,
    indianTribe?: string | null,
    multiLats?: number | null,
    origianlField?: string | null,
    unitName?: string | null,
    gisstatusType?: string | null,
    origComplDate?: string | null,
    jurisdiction?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteWellsSubscription = {
  onDeleteWells?:  {
    __typename: "Wells",
    api: string,
    wellName: string,
    operator?: string | null,
    operatorNo?: number | null,
    fieldName?: string | null,
    groundElev?: string | null,
    kellyElev?: string | null,
    drkFloorElev?: string | null,
    coordsSurfN?: string | null,
    coordsSurfE?: string | null,
    utm?: number | null,
    latitude?: number | null,
    longitude?: number | null,
    footageNS?: number | null,
    dirNS?: string | null,
    footageEW?: string | null,
    dirEW?: string | null,
    qtrQtr?: string | null,
    section?: number | null,
    township?: string | null,
    townshipDir?: string | null,
    range?: string | null,
    rangeDir?: string | null,
    meridian?: string | null,
    county?: string | null,
    dirHoriz?: string | null,
    dirVert?: string | null,
    dirDirect?: string | null,
    confidential?: string | null,
    confRelDate?: string | null,
    leaseNumber?: string | null,
    leaseType?: string | null,
    surfaceOwner?: string | null,
    abandonDate?: string | null,
    wellStatus?: string | null,
    totCumOil?: string | null,
    totCumGas?: string | null,
    totCumWater?: string | null,
    indianTribe?: string | null,
    multiLats?: number | null,
    origianlField?: string | null,
    unitName?: string | null,
    gisstatusType?: string | null,
    origComplDate?: string | null,
    jurisdiction?: string | null,
    tdsnavajo?: string | null,
    tdswingate?: string | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};
