/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateWells = /* GraphQL */ `
  subscription OnCreateWells {
    onCreateWells {
      api
      wellname
      operator
      operatorno
      fieldname
      ground_ele
      kelly_elev
      drkfloor_e
      coordssurf
      coordssu_1
      utmzone
      latitude
      longitude
      footagens
      dir_ns
      footageew
      dir_ew
      qtrqtr
      section
      township
      townshipdi
      range
      rangedir
      meridian
      county
      dir_horiz
      dir_vert
      dir_direct
      confidenti
      confreldat
      leasenumbe
      leasetype
      surfaceown
      abandondat
      wellstatus
      welltype
      totcum_oil
      totcum_gas
      totcum_wat
      indiantrib
      multi_lats
      originalfi
      unitname
      gisstatust
      origcompld
      jurisdicti
      forklift_h
      globalid
      extent
      formationtopdepths
      netpay
      netsand
      reportsid
      tdsnavajo
      tdswingate
      thickness
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateWells = /* GraphQL */ `
  subscription OnUpdateWells {
    onUpdateWells {
      api
      wellname
      operator
      operatorno
      fieldname
      ground_ele
      kelly_elev
      drkfloor_e
      coordssurf
      coordssu_1
      utmzone
      latitude
      longitude
      footagens
      dir_ns
      footageew
      dir_ew
      qtrqtr
      section
      township
      townshipdi
      range
      rangedir
      meridian
      county
      dir_horiz
      dir_vert
      dir_direct
      confidenti
      confreldat
      leasenumbe
      leasetype
      surfaceown
      abandondat
      wellstatus
      welltype
      totcum_oil
      totcum_gas
      totcum_wat
      indiantrib
      multi_lats
      originalfi
      unitname
      gisstatust
      origcompld
      jurisdicti
      forklift_h
      globalid
      extent
      formationtopdepths
      netpay
      netsand
      reportsid
      tdsnavajo
      tdswingate
      thickness
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteWells = /* GraphQL */ `
  subscription OnDeleteWells {
    onDeleteWells {
      api
      wellname
      operator
      operatorno
      fieldname
      ground_ele
      kelly_elev
      drkfloor_e
      coordssurf
      coordssu_1
      utmzone
      latitude
      longitude
      footagens
      dir_ns
      footageew
      dir_ew
      qtrqtr
      section
      township
      townshipdi
      range
      rangedir
      meridian
      county
      dir_horiz
      dir_vert
      dir_direct
      confidenti
      confreldat
      leasenumbe
      leasetype
      surfaceown
      abandondat
      wellstatus
      welltype
      totcum_oil
      totcum_gas
      totcum_wat
      indiantrib
      multi_lats
      originalfi
      unitname
      gisstatust
      origcompld
      jurisdicti
      forklift_h
      globalid
      extent
      formationtopdepths
      netpay
      netsand
      reportsid
      tdsnavajo
      tdswingate
      thickness
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
