projects:
  utWellsapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 2
      config:
        scalars:
          AWSJSON: string
          AWSDate: string
          AWSTime: string
extensions:
  amplify:
    version: 3
